import argparse

parser=argparse.ArgumentParser(description='Pytorch Demo')
parser.add_argument('--dataset_train',type=str,default='../datasets/Maryland/train')
parser.add_argument('--dataset_val',type=str,default='../datasets/Maryland/val')
parser.add_argument('--dataset_test', type=str, default='../datasets/Maryland/test')
# parser.add_argument('-threads',type=int,default=4,help='number of threads for data loader to use')
# parser.add_argument('--batchSize',type=int,default=64,help='training batch size')
parser.add_argument('--batchSize',type=int,default=16,help='training batch size')
parser.add_argument('--net',type=str,default='ITFNet',help='network')
parser.add_argument('--lr', type=float, default=0.0001, help='Learning Rate. Default=0.001')
parser.add_argument('--cuda', default=True, help='use cuda?')
parser.add_argument('--gpu_id', default=3, type=int,help='GPU ID to use')
parser.add_argument('--log', default='log_SMD/', type=str)
parser.add_argument('--best_model', default='bestmodel_dir/', type=str)
parser.add_argument('--backup', default='backup_dir/', type=str)
parser.add_argument('--train_path', default='train_image/', type=str)
parser.add_argument('--val_path', default='val_image/', type=str)
parser.add_argument('--ori_path', default='ori_image/', type=str)
parser.add_argument('--start_epoch', type=int, default=1,help='Manual epoch number (useful on restarts)')
parser.add_argument('--nEpochs', type=int, default=10000, help='number of epochs to train for')
parser.add_argument('--val_freq', type=int, default=50, help='number of epochs to test')
# parser.add_argument('--iteration', type=int, default=10, help='in one epoch the number of iteration to put out loss ')
# parser.add_argument("--step", type=int, default=500, help="Sets the learning rate to the initial LR decayed by momentum every n epochs, Default: n=500")
parser.add_argument('--seed', type=int, default=123, help='random seed to use. Default=123')
parser.add_argument("--resume", type=str,default="",  help="Path to checkpoint (default: none)")
parser.add_argument("--train_log", type=str,default="",  help="Path to save train log (default: none)")
parser.add_argument("--epoch_time_log", type=str,default="",  help="Path to save epoch time log (default: none)")
parser.add_argument("--val_log", type=str,default="",  help="Path to save validation log (default: none)")
parser.add_argument("--pretrained", type=str,default="",  help="path to pretrained model (default: none)")

opt = parser.parse_args()
